#ifndef GUARD_CONSTANTS_SHADOW_POKEMON_H
#define GUARD_CONSTANTS_SHADOW_POKEMON_H

enum {
    SHADOW_LIST_NONE,
    SHADOW_LIST_EEVEE,
    SHADOW_LIST_VAPOREON,
    SHADOW_LIST_JOLTEON,
    SHADOW_LIST_FLAREON,
    SHADOW_LIST_LEAFEON,
    SHADOW_LIST_GLACEON,
    SHADOW_LIST_LUGIA,

    //After 250, there are five "generic" Shadow Pokemon to fill in Shadow data easily for any other Trainer mon
    SHADOW_LIST_GENERIC_1 = 251,
    SHADOW_LIST_GENERIC_2 = 252,
    SHADOW_LIST_GENERIC_3 = 253,
    SHADOW_LIST_GENERIC_4 = 254,
    SHADOW_LIST_GENERIC_5 = 255,
    SHADOW_LIST_MAX = 256
};

#define SHADOW_LIST_COUNT   (SHADOW_LIST_LUGIA + 1)
#define SHADOW_LIST_GENERIC 250

#endif // GUARD_CONSTANTS_SHADOW_POKEMON_H